name: cows_care
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  file_picker: ^9.0.0
  # tflite_flutter: ^0.11.0  # لا نحتاج tflite_flutter_helper
  image: ^4.1.7  # لمعالجة الصور
  path_provider: ^2.1.2
  sqflite: ^2.4.2  # لـ Android و iOS
  sqflite_common_ffi: ^2.3.0  # لـ Windows فقط
  fl_chart: ^0.71.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/cow_icon.png
    - assets/icon/
    # - assets/cattle_disease_model.tflite
    - assets/labels.txt
