// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJBWcZlYeAwAMRfQxZpriLzFUUrxUAxxE',
    appId: '1:659657515243:web:00415f60e4dec834ea5eae',
    messagingSenderId: '659657515243',
    projectId: 'fcai-514d7',
    authDomain: 'fcai-514d7.firebaseapp.com',
    storageBucket: 'fcai-514d7.firebasestorage.app',
    measurementId: 'G-ZW4NC0VFLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtzQscpFc5RPveML5G2gQ0gu8U4s9Gl0s',
    appId: '1:659657515243:android:80104f22b0973194ea5eae',
    messagingSenderId: '659657515243',
    projectId: 'fcai-514d7',
    storageBucket: 'fcai-514d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeaq3ieAE1ogq4fCTM8NwntkQFpCiqCPo',
    appId: '1:659657515243:ios:eda1de8590274abeea5eae',
    messagingSenderId: '659657515243',
    projectId: 'fcai-514d7',
    storageBucket: 'fcai-514d7.firebasestorage.app',
    iosClientId: '659657515243-j2hv3e6tt1hpuapp7bm2tn8ra5d1kpo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cowsCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeaq3ieAE1ogq4fCTM8NwntkQFpCiqCPo',
    appId: '1:659657515243:ios:eda1de8590274abeea5eae',
    messagingSenderId: '659657515243',
    projectId: 'fcai-514d7',
    storageBucket: 'fcai-514d7.firebasestorage.app',
    iosClientId: '659657515243-j2hv3e6tt1hpuapp7bm2tn8ra5d1kpo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cowsCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJBWcZlYeAwAMRfQxZpriLzFUUrxUAxxE',
    appId: '1:659657515243:web:01bb57df78229d28ea5eae',
    messagingSenderId: '659657515243',
    projectId: 'fcai-514d7',
    authDomain: 'fcai-514d7.firebaseapp.com',
    storageBucket: 'fcai-514d7.firebasestorage.app',
    measurementId: 'G-RZNH20Y48D',
  );
}
